name: Check Docker Base Image

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: puche
  DOCKERHUB_IMAGE: webhook
  DOCKERHUB_PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7
  DOCKERHUB_BASE_IMAGE: ncarlier/webhookd:latest

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      needs-updating: ${{ steps.check.outputs.needs-updating }}
    steps:
      - name: Check update of base image
        id: check
        uses: lucacome/docker-image-update-checker@v1
        with:
          base-image: ${{ env.DOCKERHUB_BASE_IMAGE }}
          image: ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_IMAGE }}:latest
#          platforms: linux/amd64,linux/arm64
#          platforms: ${{ env.DOCKERHUB_PLATFORMS }}

  build:
    needs: check
    if: needs.check.outputs.needs-updating == 'true'
    uses: ./.github/workflows/build_docker_images.yml
    secrets: inherit
